# Generated by Django 3.2.7 on 2021-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Город')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Долгота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('weather_condition', models.JSONField(null=True, verbose_name='Погода (JSON)')),
            ],
        ),
    ]
