# Generated by Django 3.2.7 on 2021-09-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityweather',
            old_name='weather_condition',
            new_name='weather_json',
        ),
    ]
