# Generated by Django 3.2.7 on 2021-09-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('photo', models.ImageField(upload_to='form_app/photos', verbose_name='Фотография')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='SLUG')),
            ],
        ),
    ]
