# Generated by Django 3.2.7 on 2021-10-01 16:25

import django.core.validators
from django.db import migrations, models
import form_app.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Разрешённые почтовые домены: mail.ru, yandex.ru, gmail.com', whitelist=['mail.ru', 'yandex.ru', 'gmail.com'])], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], message='Имя|Фамилия должно начинаться с только с буквы!', regex='^\\w')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], message='Имя|Фамилия должно начинаться с только с буквы!', regex='^\\w')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='form_app/photos', validators=[form_app.models.file_size], verbose_name='Фотография'),
        ),
    ]
