# Generated by Django 3.2.7 on 2021-10-01 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email', whitelist=['my_domain', 'my_host'])], verbose_name='Электронная почта'),
        ),
    ]
