# Generated by Django 3.2.7 on 2021-09-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Автор статьи')),
                ('title', models.CharField(max_length=45, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации статьи')),
            ],
        ),
    ]
